domain_path: C:\Users\Admin\Desktop\ANUL3_SEM1\SSC_Proiect\platforma_vitis\platforma\zynq_fsbl\zynq_fsbl_bsp
app_src_dir: D:\InstalareVivado\Vitis\2024.1\data\embeddedsw\lib\sw_apps\zynq_fsbl
template: zynq_fsbl
